import test from 'node:test';
import assert from 'node:assert/strict';
import { scryptSync, randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { createMonitor, digest } from '../server.mjs';
import { normalizeSlurm } from '../slurm/schema.mjs';

test('Slurm ingestion isolates source tokens, protects data, preserves last success and restores stale cache', async t => {
  const dir=mkdtempSync(join(tmpdir(),'slurm-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
  let clock=Date.now();const salt='a'.repeat(48),password='test-only';
  const source={id:'cluster-demo',name:'Demo Cluster',collectorUser:'alice',scope:'visible',visibility:'private-jobs',intervalSeconds:60,tokenHash:digest('slurm-token')};
  const config={username:'admin',passwordSalt:salt,passwordHash:scryptSync(password,salt,64).toString('hex'),secureCookies:false,publicOrigin:'https://test.example',hosts:[{id:'gpu',name:'GPU',tokenHash:digest('gpu-token')}],slurmSources:[source],slurmStateFile:join(dir,'slurm.json')};
  const server=createMonitor(config,{now:()=>clock});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>server.close());
  const base='http://127.0.0.1:'+server.address().port;
  const req=(path,options)=>fetch(base+path,options);
  const post=(body,headers={})=>({method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
  const auth={Authorization:'Bearer slurm-token','X-Source-Id':'cluster-demo'};
  assert.equal((await req('/api/slurm')).status,401);
  assert.equal((await req('/api/slurm',{headers:auth})).status,401);
  assert.equal((await req('/api/slurm/ingest',post({}, {'X-Source-Id':'cluster-demo',Authorization:'Bearer gpu-token'}))).status,401);
  assert.equal((await req('/api/ingest',post({}, {'X-Host-Id':'gpu',Authorization:'Bearer slurm-token'}))).status,401);
  assert.equal((await req('/api/slurm/ingest',post({sourceId:'other'},auth))).status,403);
  const packet={version:1,sourceId:'cluster-demo',reportId:randomUUID(),collectedAt:Date.now(),scope:'visible',queueAgeMs:2000,jobs:[{jobId:'123',username:'alice',partition:'long',state:'PENDING',nodes:1,cpus:8,memory:'32G',elapsed:'0:00',elapsedSeconds:0,pendingSeconds:45,timeLimit:'1-00:00:00',priority:99,reason:'Resources',tres:'gres/gpu=2',command:'SHOULD NOT BE RETAINED',workDir:'/secret'}],partitions:[{name:'long',availability:'up',nodes:10,state:'mix-'}],error:null};
  assert.equal((await req('/api/slurm/ingest',post(packet,auth))).status,200);
  assert.equal((await req('/api/slurm/ingest',post(packet,auth))).status,409);
  const login=await req('/api/login',post({username:'admin',password},{Origin:config.publicOrigin}));
  const Cookie=login.headers.get('set-cookie').split(';')[0];
  let result=await(await req('/api/slurm',{headers:{Cookie}})).json();
  assert.equal(result.sources[0].counts.pending,1);
  assert.equal(result.sources[0].status,'online');
  assert.equal(result.sources[0].jobSampledAt,clock-2000);
  assert.equal(result.sources[0].jobs[0].pendingSeconds,45);
  const sampledAt=result.sources[0].jobSampledAt;
  assert.ok(!JSON.stringify(result).includes('SHOULD NOT BE RETAINED'));
  assert.ok(!JSON.stringify(result).includes('tokenHash'));
  clock+=15000;
  assert.equal((await req('/api/slurm/ingest',post({...packet,reportId:randomUUID(),error:'Query timeout',jobs:[],partitions:[]},auth))).status,200);
  result=await(await req('/api/slurm',{headers:{Cookie}})).json();
  assert.equal(result.sources[0].status,'error');assert.equal(result.sources[0].jobs[0].jobId,'123');
  assert.equal(result.sources[0].jobSampledAt,sampledAt,'error heartbeat must not reset the timing baseline');
  clock+=181000;
  result=await(await req('/api/slurm',{headers:{Cookie}})).json();assert.equal(result.sources[0].status,'offline');
  const restarted=createMonitor(config,{now:()=>clock});restarted.listen(0,'127.0.0.1');await once(restarted,'listening');t.after(()=>restarted.close());
  const base2='http://127.0.0.1:'+restarted.address().port;
  const login2=await fetch(base2+'/api/login',post({username:'admin',password},{Origin:config.publicOrigin}));
  const restored=await(await fetch(base2+'/api/slurm',{headers:{Cookie:login2.headers.get('set-cookie').split(';')[0]}})).json();
  assert.equal(restored.sources[0].jobs[0].jobId,'123');assert.equal(restored.sources[0].status,'offline');
  assert.throws(()=>normalizeSlurm({...packet,scope:'mine',jobs:[{...packet.jobs[0],username:'someone-else'}]},{...source,scope:'mine'}));
  assert.throws(()=>normalizeSlurm({...packet,jobs:[packet.jobs[0],packet.jobs[0]]},source));
});
